docker_repo: docker-ce.repo

# Docker user
docker_user: denzell

# Web server
web_docker_img_name: web
web_docker_img_tag: latest
web_container_name: webserver
web_ports: 8084:80
web_dockerfile_path: docker/web/

# Database server
db_docker_img_name: database
db_docker_img_tag: latest
db_container_name: dbaseserver
db_ports: 3306:3306
db_dockerfile_path: docker/database/
